### ISSUE TITLE
z.input, z.get functions not found with %r

### ISSUE THREAD

**Issue by piersharding** [elbamos/Zeppelin-With-R#13]
Hi -

I'm getting error messages like:

```
  <simpleError in eval(expr, envir, enclos): could not find function "z.get">
```

when accessing the z object under the %r interpreter using an example from the 'R Tutorial' notebook, eg:

```
%r 
z.input("name", "sun")
print(paste0("%html Hello ", z.input("name", "sun")))
```

Output:

```
z.input("name", "sun")
<simpleError in eval(expr, envir, enclos): could not find function "z.input">
```

This is using the recently merged PR into upstream for the rinterpreter (not sure if you want issues recorded here any more ...).
Any ideas what might be going on here?

Thanks,
Piers Harding.

**Comment by elbamos** [comment]
@piersharding The command should be ".z.input()" with a "." before the "z". 

If that doesn't work please let me know as soon as you can  There were two interpreters merged at the same time, and I'm concerned that there may be a conflict between them.

**Comment by piersharding** [comment]
That fixed it - thanks very much.  All the examples from the sample notebook had the same problem.

Cheers,
Piers.

**Comment by elbamos** [comment]
It's not a problem, it's a feature ;)

BTW - the .z.show() functions in the demo notebook are no longer present because they're no longer necessary, since the relevant visualization packages now are much simpler to work with.

Feel free to ping me here or on the zeppelin mailing list if you have any issues.

Thanks, Piers.
