### ISSUE TITLE
ERROR RInterpreter$: <simpleError in get object '.createDataFrame' not found>

### ISSUE THREAD

**Issue by QuantScientist3** [elbamos/Zeppelin-With-R#7]
Hi,
Is this the correct way to access/invoke SparkR? like so SparkR:::. ? 

%spark.r
library(SparkR)
sc
print(Sys.getenv("SPARK_HOME"))

df <-SparkR:::.createDataFrame(sc, faithful) 
head(df)
# Print its schema

SparkR:::.printSchema(df)

**Comment by elbamos** [comment]
No - %sparkr is not an interpreter. %spark.r is what you want.  Also, you shouldn't ever need to load the SparkR library explicitly. If it's available, it'll be injected into the environment automatically. 

Finally, sometimes, depending on your system, you may need to call SparkR:::head instead of head(). This seems to be dependent on the version of Spark.

**Comment by QuantScientist3** [comment]
Listen .... I spent so much time trying to make this work ... without the library(SparkR) nothing seems to work ... I cant even use the databricks lib to load a CSV.

Also, when using SparkR:::head as you asked I get:

SparkR:::head(df) <simpleError in invokeJava(isStatic = TRUE, className, methodName, ...): org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 5, localhost): java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) at org.apache.spark.api.r.RRDD$.createRProcess(RRDD.scala:407) at org.apache.spark.api.r.RRDD$.createRWorker(RRDD.scala:423) at org.apache.spark.api.r.BaseRRDD.compute(RRDD.scala:62) at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297) at org.apache.spark.rdd.RDD.iterator(RDD.scala:264) at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38) at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297) at org.apache.spark.rdd.RDD.iterator(RDD.scala:264) at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38) at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297) at org.apache.spark.rdd.RDD.iterator(RDD.scala:264) at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38) at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297) at org.apache.spark.rdd.RDD.iterator(RDD.scala:264) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66) at org.apache.spark.scheduler.Task.run(Task.scala:88) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.io.IOException: error=2, No such file or directory at java.lang.UNIXProcess.forkAndExec(Native Method) at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) at java.lang.ProcessImpl.start(ProcessImpl.java:134) at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ... 20 more

**Comment by elbamos** [comment]
If nothing works without `library(SparkR)`, that means that Zeppelin and Spark aren't talking to each other.  Usually (in 100% of the problem reports I've seen), that means the `SPARK_HOME` environment variable isn't set properly. 

(You said you're using `%sparkr` as opposed to `%spark.r`.  If that was not a typo let me know, because that implies that something very different is happening.)

The first thing the R interpreter does after it starts R, is to try to load the `SparkR` library from under SPARK_HOME. 

Can you upload a log?  Delete the contents of the ZEPPELIN_HOME/log folder, then start Zeppelin and try running the first three cells of the R interpreter notebook.

**Comment by GP-GPU** [comment]
I moved to Jupyter ... thanks a lot for all your help.
